import json
import logging
import os
import time
from typing import Any, Dict, List

import requests

logger = logging.getLogger(__name__)


class TelegramBot:
    def __init__(self, token: str, chat_id: str, coin_strong_enabled: bool = True):
        self.token = token
        self.chat_id = chat_id
        self.base = f"https://api.telegram.org/bot{token}"
        self.coin_strong_enabled = bool(coin_strong_enabled)
        self._last_update_id = 0

    def send_message(self, text: str) -> Dict[str, Any]:
        if not self.token or not self.chat_id:
            logger.warning("Telegram bot not configured. Message skipped.")
            return {"ok": False, "reason": "not_configured"}
        payload = {
            "chat_id": self.chat_id,
            "text": text,
            "parse_mode": "HTML",
        }
        url = f"{self.base}/sendMessage"
        try:
            response = requests.post(url, json=payload, timeout=(5, 10))
            response.raise_for_status()
            body = response.json()
            if body.get("ok") is False:
                logger.warning("Telegram API rejected message: %s", body)
            return body
        except Exception as exc:  # pragma: no cover - network failure path
            logger.exception("Telegram send failed for chat_id=%s. Payload=%s", self.chat_id, text)
            return {"ok": False, "error": str(exc)}

    def render_signal(self, signal: Dict[str, Any]) -> str:
        if not signal or signal.get("direction") == "neutral":
            return ""

        symbol = signal.get("symbol", "UNKNOWN")
        direction = str(signal.get("direction", "")).upper()
        score = signal.get("score", 0)
        confidence = signal.get("confidence", 0)
        entry = signal.get("entry", "-")
        sl = signal.get("sl", "-")
        tp = signal.get("tp", "-")
        module = signal.get("module") or signal.get("signal_module") or "composite"
        regime = signal.get("regime") or "mixed"
        confluence = signal.get("confluence") or {}
        timeframe_text = " | ".join(f"{tf}:{dir_}" for tf, dir_ in confluence.items()) if isinstance(confluence, dict) else "-"
        correlated = signal.get("correlated_with") or []
        group_name = signal.get("group_key") or ""
        correlated_text = ""
        if correlated:
            correlated_text = f"Correlated: {', '.join(str(item) for item in correlated)}"
            if group_name and group_name != symbol:
                correlated_text += f" (group: {group_name})"

        long_short = signal.get("long_short") or {}
        ratio_line = ""
        if isinstance(long_short, dict) and long_short:
            ratio_value = long_short.get("aggregated_ratio")
            if ratio_value is None:
                logger.warning("Telegram render skipped long/short ratio for %s: no aggregated_ratio in signal payload", symbol)
            else:
                ratio_value = float(ratio_value)
                if ratio_value > 0.5:
                    bias = "retail leaning long"
                elif ratio_value < 0.5:
                    bias = "retail leaning short"
                else:
                    bias = "balanced"
                ratio_line = f"Long/Short ratio: {ratio_value:.2f} ({bias})"
        elif signal.get("long_short") is not None:
            logger.warning("Telegram render skipped long/short ratio for %s: long_short payload empty or invalid", symbol)

        reasons = signal.get("reasons") or []
        reason_text = "\n".join(f"• {reason}" for reason in reasons[:3]) if reasons else "• Signal generated by composite model"

        lines = [
            f"<b>{symbol}</b>  <b>{direction}</b>",
            f"Module: <b>{module}</b> | Regime: <b>{regime}</b>",
            f"Score: <b>{score}</b> | Confidence: <b>{confidence}</b>",
            f"Entry: {entry} | SL: {sl} | TP: {tp}",
            f"Timeframes: {timeframe_text}",
        ]
        if correlated_text:
            lines.append(correlated_text)
        if ratio_line:
            lines.append(ratio_line)
        lines.append(reason_text)
        return "\n".join(lines)

    def render_hit_notice(self, signal: Dict[str, Any]) -> str:
        symbol = signal.get("symbol", "UNKNOWN")
        direction = str(signal.get("direction", "")).upper()
        hit_type = str(signal.get("hit_type", "tp")).upper()
        price = signal.get("price", signal.get("current_price", "-"))
        entry = signal.get("entry", "-")
        sl = signal.get("sl", "-")
        tp = signal.get("tp", "-")
        label = "chạm SL" if hit_type == "SL" else "chạm TP"
        return (
            f"<b>{symbol}</b>  <b>{direction}</b>  <b>{label}</b>\n"
            f"Entry: {entry} | Price: {price} | SL: {sl} | TP: {tp}\n"
            f"Kèo này đã {label.lower()} và đang được đóng theo logic tín hiệu"
        )

    def parse_command(self, text: str) -> Dict[str, Any]:
        command = (text or "").strip()
        normalized = command.lower()
        if not normalized.startswith("/coinstrong"):
            return {"action": "unknown", "enabled": self.coin_strong_enabled, "raw": command}

        remainder = normalized[len("/coinstrong"):].strip()
        if remainder in {"", "toggle", "t"}:
            return {"action": "toggle", "enabled": not self.coin_strong_enabled, "raw": command}
        if remainder in {"on", "enable", "1", "true"}:
            return {"action": "enable", "enabled": True, "raw": command}
        if remainder in {"off", "disable", "0", "false"}:
            return {"action": "disable", "enabled": False, "raw": command}
        return {"action": "toggle", "enabled": not self.coin_strong_enabled, "raw": command}

    def poll_commands(self) -> List[Dict[str, Any]]:
        if not self.token:
            return []

        url = f"{self.base}/getUpdates"
        backoff = 5
        max_retries = 5

        for attempt in range(max_retries):
            try:
                response = requests.get(
                    url,
                    params={"timeout": 5, "offset": self._last_update_id + 1},
                    timeout=(5, 10),
                )

                if response.status_code == 409 or "Conflict" in str(response.text).lower():
                    logger.warning(
                        "Telegram getUpdates conflict (409): another process is using the same token. Retrying in %s seconds.",
                        backoff,
                    )
                    time.sleep(backoff)
                    backoff = min(backoff * 2, 30)
                    continue

                response.raise_for_status()
                payload = response.json()
                break
            except Exception as exc:
                if isinstance(exc, requests.HTTPError) and getattr(exc.response, "status_code", None) == 409:
                    logger.warning(
                        "Telegram getUpdates 409 conflict: another process is using the same token. Retrying in %s seconds.",
                        backoff,
                    )
                    time.sleep(backoff)
                    backoff = min(backoff * 2, 30)
                    continue
                logger.warning("Telegram polling failed: %s", exc)
                return []
        else:
            logger.warning("Telegram getUpdates retry limit reached after repeated 409 conflicts. Waiting for next cycle.")
            return []

        if not isinstance(payload, dict):
            return []

        updates = payload.get("result", [])
        commands: List[Dict[str, Any]] = []
        for update in updates:
            update_id = int(update.get("update_id", 0))
            if update_id <= self._last_update_id:
                continue
            self._last_update_id = max(self._last_update_id, update_id)
            message = update.get("message") or {}
            text = message.get("text") or ""
            if not text:
                continue
            commands.append({"text": text, "chat_id": str(message.get("chat", {}).get("id", self.chat_id))})
        return commands

    def render_summary_top_coins(self, ranked: List[Dict[str, Any]]) -> str:
        if not ranked:
            return "<b>TOP COIN</b>\nNo active coin ranked above threshold"

        lines = ["<b>TOP COIN</b>"]
        for idx, item in enumerate(ranked[:5], start=1):
            symbol = item.get("symbol", "UNKNOWN")
            direction = str(item.get("direction", "neutral")).upper()
            score = item.get("score", 0)
            priority = item.get("priority", 0)
            lines.append(f"{idx}. <b>{symbol}</b> {direction} | score {score} | priority {priority}")
        return "\n".join(lines)

    def send_signal(self, signal: Dict[str, Any]) -> bool:
        message = self.render_signal(signal)
        if not message:
            return False
        result = self.send_message(message)
        return bool(result.get("ok"))

    def send_hit_notice(self, signal: Dict[str, Any]) -> bool:
        message = self.render_hit_notice(signal)
        if not message:
            return False
        result = self.send_message(message)
        return bool(result.get("ok"))

    def send_summary_top_coins(self, ranked: List[Dict[str, Any]]) -> bool:
        summary = self.render_summary_top_coins(ranked)
        if not summary:
            return False
        result = self.send_message(summary)
        return bool(result.get("ok"))
