import json
import logging
import os
from typing import Any, Dict

import requests

logger = logging.getLogger(__name__)


class TelegramBot:
    def __init__(self, token: str, chat_id: str):
        self.token = token
        self.chat_id = chat_id
        self.base = f"https://api.telegram.org/bot{token}"

    def send_message(self, text: str) -> Dict[str, Any]:
        if not self.token or not self.chat_id:
            logger.warning("Telegram bot not configured. Message skipped.")
            return {"ok": False, "reason": "not_configured"}
        payload = {
            "chat_id": self.chat_id,
            "text": text,
            "parse_mode": "HTML",
        }
        url = f"{self.base}/sendMessage"
        try:
            response = requests.post(url, data=payload, timeout=10)
            response.raise_for_status()
            return response.json()
        except Exception as exc:  # pragma: no cover - network failure path
            logger.warning("Telegram send failed: %s", exc)
            return {"ok": False, "error": str(exc)}

    def render_signal(self, signal: Dict[str, Any]) -> str:
        if not signal or signal.get("direction") == "neutral":
            return ""

        symbol = signal.get("symbol", "UNKNOWN")
        direction = str(signal.get("direction", "")).upper()
        score = signal.get("score", 0)
        confidence = signal.get("confidence", 0)
        entry = signal.get("entry", "-")
        sl = signal.get("sl", "-")
        tp = signal.get("tp", "-")
        module = signal.get("module") or signal.get("signal_module") or "composite"
        regime = signal.get("regime") or "mixed"
        confluence = signal.get("confluence") or {}
        timeframe_text = " | ".join(f"{tf}:{dir_}" for tf, dir_ in confluence.items()) if isinstance(confluence, dict) else "-"
        reasons = signal.get("reasons") or []
        reason_text = "\n".join(f"• {reason}" for reason in reasons[:3]) if reasons else "• Signal generated by composite model"

        return (
            f"<b>{symbol}</b>  <b>{direction}</b>\n"
            f"Module: <b>{module}</b> | Regime: <b>{regime}</b>\n"
            f"Score: <b>{score}</b> | Confidence: <b>{confidence}</b>\n"
            f"Entry: {entry} | SL: {sl} | TP: {tp}\n"
            f"Timeframes: {timeframe_text}\n"
            f"{reason_text}"
        )

    def send_signal(self, signal: Dict[str, Any]) -> bool:
        message = self.render_signal(signal)
        if not message:
            return False
        result = self.send_message(message)
        return bool(result.get("ok"))
